{% set name = "databricks-sdk" %}
{% set version = "0.17.0" %}
{% set sha256 = "0a1baa6783aba9b034b9a017da8d0cf839ec61ae8318792b78bfb3db0374dd9c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/databricks-sdk-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.28.1,<3
    - google-auth >=2.0

test:
  imports:
    - databricks
    - databricks.sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/databricks/databricks-sdk-py
  summary: Databricks SDK for Python (Experimental)
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - jasongrout-db
    - nfx
    - monaldoj
