{% set name = "databricks-sdk" %}
{% set version = "0.34.0" %}
{% set sha256 = "1d4ec47783cf17cb6fc2aec43025625e04519f01dbb1696d621ed3cacdb64eb5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.28.1,<3
    - google-auth >=2.0,<3

test:
  imports:
    - databricks
    - databricks.sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/databricks/databricks-sdk-py
  summary: Databricks SDK for Python (Experimental)
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - jasongrout-db
    - nfx
    - monaldoj
