{% set name = "databricks-sdk" %}
{% set version = "0.36.0" %}
{% set sha256 = "d8c46348cbd3e0b56991a6b7a59d7a6e0437947f6387bef832e6fe092e2dd427" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - requests >=2.28.1,<3
    - google-auth >=2.0,<3

test:
  imports:
    - databricks
    - databricks.sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/databricks/databricks-sdk-py
  summary: Databricks SDK for Python (Experimental)
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - jasongrout-db
    - nfx
    - monaldoj
