{% set name = "databricks-sdk" %}
{% set version = "0.73.0" %}
{% set sha256 = "db09eaaacd98e07dded78d3e7ab47d2f6c886e0380cb577977bd442bace8bd8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - protobuf
  run:
    - python >={{ python_min }}
    - requests >=2.28.1,<3
    - google-auth >=2.0,<3
    - protobuf

test:
  imports:
    - databricks
    - databricks.sdk
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/databricks/databricks-sdk-py
  summary: Databricks SDK for Python (Experimental)
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - jasongrout-db
    - nfx
    - monaldoj
